version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: UTC
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - java
    groups:
      grpc-protobuf:
        patterns:
          - "io.grpc*"
          - "com.google.protobuf*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: UTC
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github-actions
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action*"
